version: '3'
services:
  db:
    image: chenxinaz/zhparser
    restart: always
    volumes:
      - ./tmp/db:/var/lib/postgresql
  web:
    build: .
    entrypoint: [bin/entry]
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    ports:
      - "3000:3000"
    depends_on:
      - db